{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3d38e6f6-f56d-48de-9624-f8e479bdb405",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Title</th>\n",
       "      <th>Release Date</th>\n",
       "      <th>Developer</th>\n",
       "      <th>Publisher</th>\n",
       "      <th>Genres</th>\n",
       "      <th>Product Rating</th>\n",
       "      <th>User Score</th>\n",
       "      <th>User Ratings Count</th>\n",
       "      <th>Platforms Info</th>\n",
       "      <th>Platforms Info Cleaned</th>\n",
       "      <th>Platform Metascores</th>\n",
       "      <th>Platform Metascore Counts</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Ziggurat (2012)</td>\n",
       "      <td>17/2/2012</td>\n",
       "      <td>Action Button Entertainment</td>\n",
       "      <td>Freshuu Inc.</td>\n",
       "      <td>Action</td>\n",
       "      <td>Not Rated</td>\n",
       "      <td>6.900000</td>\n",
       "      <td>14.0</td>\n",
       "      <td>[{'Platform': 'iOS (iPhone/iPad)', 'Platform M...</td>\n",
       "      <td>iOS (iPhone/iPad)</td>\n",
       "      <td>83</td>\n",
       "      <td>Based on 18 Critic Reviews</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>4X4 EVO 2</td>\n",
       "      <td>15/11/2001</td>\n",
       "      <td>Terminal Reality</td>\n",
       "      <td>Gathering</td>\n",
       "      <td>Auto Racing Sim</td>\n",
       "      <td>Rated E For Everyone</td>\n",
       "      <td>6.894852</td>\n",
       "      <td>NaN</td>\n",
       "      <td>[{'Platform': 'Xbox', 'Platform Metascore': '5...</td>\n",
       "      <td>Xbox, PC, GameCube</td>\n",
       "      <td>59, 69, 56</td>\n",
       "      <td>Based on 15 Critic Reviews, Based on 9 Critic ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>MotoGP 2 (2001)</td>\n",
       "      <td>22/1/2002</td>\n",
       "      <td>Namco</td>\n",
       "      <td>Namco</td>\n",
       "      <td>Auto Racing Sim</td>\n",
       "      <td>Rated E For Everyone</td>\n",
       "      <td>5.800000</td>\n",
       "      <td>NaN</td>\n",
       "      <td>[{'Platform': 'PlayStation 2', 'Platform Metas...</td>\n",
       "      <td>PlayStation 2</td>\n",
       "      <td>78</td>\n",
       "      <td>Based on 18 Critic Reviews</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Gothic 3</td>\n",
       "      <td>14/11/2006</td>\n",
       "      <td>Piranha Bytes</td>\n",
       "      <td>Aspyr</td>\n",
       "      <td>Western RPG</td>\n",
       "      <td>Rated T For Teen</td>\n",
       "      <td>7.500000</td>\n",
       "      <td>832.0</td>\n",
       "      <td>[{'Platform': 'PC', 'Platform Metascore': '63'...</td>\n",
       "      <td>PC</td>\n",
       "      <td>63</td>\n",
       "      <td>Based on 39 Critic Reviews</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Siege Survival: Gloria Victis</td>\n",
       "      <td>18/5/2021</td>\n",
       "      <td>FishTankStudio</td>\n",
       "      <td>Black Eye Games</td>\n",
       "      <td>RPG</td>\n",
       "      <td>Not Rated</td>\n",
       "      <td>6.500000</td>\n",
       "      <td>10.0</td>\n",
       "      <td>[{'Platform': 'PC', 'Platform Metascore': '69'...</td>\n",
       "      <td>PC</td>\n",
       "      <td>69</td>\n",
       "      <td>Based on 12 Critic Reviews</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                           Title Release Date                    Developer  \\\n",
       "0                Ziggurat (2012)    17/2/2012  Action Button Entertainment   \n",
       "1                      4X4 EVO 2   15/11/2001             Terminal Reality   \n",
       "2                MotoGP 2 (2001)    22/1/2002                        Namco   \n",
       "3                       Gothic 3   14/11/2006                Piranha Bytes   \n",
       "4  Siege Survival: Gloria Victis    18/5/2021               FishTankStudio   \n",
       "\n",
       "         Publisher           Genres        Product Rating  User Score  \\\n",
       "0     Freshuu Inc.           Action             Not Rated    6.900000   \n",
       "1        Gathering  Auto Racing Sim  Rated E For Everyone    6.894852   \n",
       "2            Namco  Auto Racing Sim  Rated E For Everyone    5.800000   \n",
       "3            Aspyr      Western RPG      Rated T For Teen    7.500000   \n",
       "4  Black Eye Games              RPG             Not Rated    6.500000   \n",
       "\n",
       "   User Ratings Count                                     Platforms Info  \\\n",
       "0                14.0  [{'Platform': 'iOS (iPhone/iPad)', 'Platform M...   \n",
       "1                 NaN  [{'Platform': 'Xbox', 'Platform Metascore': '5...   \n",
       "2                 NaN  [{'Platform': 'PlayStation 2', 'Platform Metas...   \n",
       "3               832.0  [{'Platform': 'PC', 'Platform Metascore': '63'...   \n",
       "4                10.0  [{'Platform': 'PC', 'Platform Metascore': '69'...   \n",
       "\n",
       "  Platforms Info Cleaned Platform Metascores  \\\n",
       "0      iOS (iPhone/iPad)                  83   \n",
       "1     Xbox, PC, GameCube          59, 69, 56   \n",
       "2          PlayStation 2                  78   \n",
       "3                     PC                  63   \n",
       "4                     PC                  69   \n",
       "\n",
       "                           Platform Metascore Counts  \n",
       "0                         Based on 18 Critic Reviews  \n",
       "1  Based on 15 Critic Reviews, Based on 9 Critic ...  \n",
       "2                         Based on 18 Critic Reviews  \n",
       "3                         Based on 39 Critic Reviews  \n",
       "4                         Based on 12 Critic Reviews  "
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# Correct file path\n",
    "path = r'C:\\Users\\User\\Documents\\NewDataSet.csv'\n",
    "\n",
    "# Load the data\n",
    "df = pd.read_csv(path)\n",
    "\n",
    "# Display the first few rows\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "bccd6fac-9311-4bf0-ab5c-2b2674f3d0cf",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<bound method NDFrame.head of         user_id                                              Title  user_score\n",
       "0        user_9                                    Ziggurat (2012)        3.01\n",
       "1       user_81                                    Ziggurat (2012)        7.79\n",
       "2       user_66                                    Ziggurat (2012)        8.31\n",
       "3       user_47                                    Ziggurat (2012)        8.40\n",
       "4       user_49                                    Ziggurat (2012)        2.72\n",
       "...         ...                                                ...         ...\n",
       "211315  user_51  Lemony Snicket's A Series of Unfortunate Event...        3.11\n",
       "211316  user_62  Lemony Snicket's A Series of Unfortunate Event...        4.84\n",
       "211317  user_77  Lemony Snicket's A Series of Unfortunate Event...        2.53\n",
       "211318  user_74  Lemony Snicket's A Series of Unfortunate Event...        9.68\n",
       "211319  user_92  Lemony Snicket's A Series of Unfortunate Event...        9.68\n",
       "\n",
       "[211320 rows x 3 columns]>"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "path = r'C:\\Users\\User\\Downloads\\User_Dataset.csv'\n",
    "\n",
    "userset = pd.read_csv(path)\n",
    "\n",
    "userset.head"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "9ae4d353-7631-4906-85eb-20b29373e880",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Title</th>\n",
       "      <th>Release Date</th>\n",
       "      <th>Developer</th>\n",
       "      <th>Publisher</th>\n",
       "      <th>Genres</th>\n",
       "      <th>Product Rating</th>\n",
       "      <th>User Score</th>\n",
       "      <th>User Ratings Count</th>\n",
       "      <th>Platforms Info</th>\n",
       "      <th>Platforms Info Cleaned</th>\n",
       "      <th>Platform Metascores</th>\n",
       "      <th>Platform Metascore Counts</th>\n",
       "      <th>user_id</th>\n",
       "      <th>user_score</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Ziggurat (2012)</td>\n",
       "      <td>17/2/2012</td>\n",
       "      <td>Action Button Entertainment</td>\n",
       "      <td>Freshuu Inc.</td>\n",
       "      <td>Action</td>\n",
       "      <td>Not Rated</td>\n",
       "      <td>6.9</td>\n",
       "      <td>14.0</td>\n",
       "      <td>[{'Platform': 'iOS (iPhone/iPad)', 'Platform M...</td>\n",
       "      <td>iOS (iPhone/iPad)</td>\n",
       "      <td>83</td>\n",
       "      <td>Based on 18 Critic Reviews</td>\n",
       "      <td>user_9</td>\n",
       "      <td>3.01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Ziggurat (2012)</td>\n",
       "      <td>17/2/2012</td>\n",
       "      <td>Action Button Entertainment</td>\n",
       "      <td>Freshuu Inc.</td>\n",
       "      <td>Action</td>\n",
       "      <td>Not Rated</td>\n",
       "      <td>6.9</td>\n",
       "      <td>14.0</td>\n",
       "      <td>[{'Platform': 'iOS (iPhone/iPad)', 'Platform M...</td>\n",
       "      <td>iOS (iPhone/iPad)</td>\n",
       "      <td>83</td>\n",
       "      <td>Based on 18 Critic Reviews</td>\n",
       "      <td>user_81</td>\n",
       "      <td>7.79</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Ziggurat (2012)</td>\n",
       "      <td>17/2/2012</td>\n",
       "      <td>Action Button Entertainment</td>\n",
       "      <td>Freshuu Inc.</td>\n",
       "      <td>Action</td>\n",
       "      <td>Not Rated</td>\n",
       "      <td>6.9</td>\n",
       "      <td>14.0</td>\n",
       "      <td>[{'Platform': 'iOS (iPhone/iPad)', 'Platform M...</td>\n",
       "      <td>iOS (iPhone/iPad)</td>\n",
       "      <td>83</td>\n",
       "      <td>Based on 18 Critic Reviews</td>\n",
       "      <td>user_66</td>\n",
       "      <td>8.31</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Ziggurat (2012)</td>\n",
       "      <td>17/2/2012</td>\n",
       "      <td>Action Button Entertainment</td>\n",
       "      <td>Freshuu Inc.</td>\n",
       "      <td>Action</td>\n",
       "      <td>Not Rated</td>\n",
       "      <td>6.9</td>\n",
       "      <td>14.0</td>\n",
       "      <td>[{'Platform': 'iOS (iPhone/iPad)', 'Platform M...</td>\n",
       "      <td>iOS (iPhone/iPad)</td>\n",
       "      <td>83</td>\n",
       "      <td>Based on 18 Critic Reviews</td>\n",
       "      <td>user_47</td>\n",
       "      <td>8.40</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Ziggurat (2012)</td>\n",
       "      <td>17/2/2012</td>\n",
       "      <td>Action Button Entertainment</td>\n",
       "      <td>Freshuu Inc.</td>\n",
       "      <td>Action</td>\n",
       "      <td>Not Rated</td>\n",
       "      <td>6.9</td>\n",
       "      <td>14.0</td>\n",
       "      <td>[{'Platform': 'iOS (iPhone/iPad)', 'Platform M...</td>\n",
       "      <td>iOS (iPhone/iPad)</td>\n",
       "      <td>83</td>\n",
       "      <td>Based on 18 Critic Reviews</td>\n",
       "      <td>user_49</td>\n",
       "      <td>2.72</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "             Title Release Date                    Developer     Publisher  \\\n",
       "0  Ziggurat (2012)    17/2/2012  Action Button Entertainment  Freshuu Inc.   \n",
       "1  Ziggurat (2012)    17/2/2012  Action Button Entertainment  Freshuu Inc.   \n",
       "2  Ziggurat (2012)    17/2/2012  Action Button Entertainment  Freshuu Inc.   \n",
       "3  Ziggurat (2012)    17/2/2012  Action Button Entertainment  Freshuu Inc.   \n",
       "4  Ziggurat (2012)    17/2/2012  Action Button Entertainment  Freshuu Inc.   \n",
       "\n",
       "   Genres Product Rating  User Score  User Ratings Count  \\\n",
       "0  Action      Not Rated         6.9                14.0   \n",
       "1  Action      Not Rated         6.9                14.0   \n",
       "2  Action      Not Rated         6.9                14.0   \n",
       "3  Action      Not Rated         6.9                14.0   \n",
       "4  Action      Not Rated         6.9                14.0   \n",
       "\n",
       "                                      Platforms Info Platforms Info Cleaned  \\\n",
       "0  [{'Platform': 'iOS (iPhone/iPad)', 'Platform M...      iOS (iPhone/iPad)   \n",
       "1  [{'Platform': 'iOS (iPhone/iPad)', 'Platform M...      iOS (iPhone/iPad)   \n",
       "2  [{'Platform': 'iOS (iPhone/iPad)', 'Platform M...      iOS (iPhone/iPad)   \n",
       "3  [{'Platform': 'iOS (iPhone/iPad)', 'Platform M...      iOS (iPhone/iPad)   \n",
       "4  [{'Platform': 'iOS (iPhone/iPad)', 'Platform M...      iOS (iPhone/iPad)   \n",
       "\n",
       "  Platform Metascores   Platform Metascore Counts  user_id  user_score  \n",
       "0                  83  Based on 18 Critic Reviews   user_9        3.01  \n",
       "1                  83  Based on 18 Critic Reviews  user_81        7.79  \n",
       "2                  83  Based on 18 Critic Reviews  user_66        8.31  \n",
       "3                  83  Based on 18 Critic Reviews  user_47        8.40  \n",
       "4                  83  Based on 18 Critic Reviews  user_49        2.72  "
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = pd.merge(df,userset, on='Title')\n",
    "data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "7c63dca2-5592-4825-b77f-a6a5a67a99ed",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Title                         6594\n",
       "Release Date                  7275\n",
       "Developer                     8342\n",
       "Publisher                     8342\n",
       "Genres                        6594\n",
       "Product Rating                   0\n",
       "User Score                       0\n",
       "User Ratings Count           47581\n",
       "Platforms Info                   0\n",
       "Platforms Info Cleaned        6718\n",
       "Platform Metascores           6718\n",
       "Platform Metascore Counts     6718\n",
       "user_id                          0\n",
       "user_score                       0\n",
       "dtype: int64"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.isna().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "3109689f-a4d3-4221-a254-a8b5a2fbdd57",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Title                        0\n",
       "Release Date                 0\n",
       "Developer                    0\n",
       "Publisher                    0\n",
       "Genres                       0\n",
       "Product Rating               0\n",
       "User Score                   0\n",
       "User Ratings Count           0\n",
       "Platforms Info               0\n",
       "Platforms Info Cleaned       0\n",
       "Platform Metascores          0\n",
       "Platform Metascore Counts    0\n",
       "user_id                      0\n",
       "user_score                   0\n",
       "dtype: int64"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = data.dropna()\n",
    "\n",
    "data.isna().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "5cdc147a-5dc5-4c42-8ba4-be26b29cc36f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Title\n",
       "Rollerdrome                   8.017273\n",
       "Dead Island: Ryder White      7.941000\n",
       "PixelJunk Shooter Ultimate    7.732000\n",
       "Mary Skelter Finale           7.730000\n",
       "Triangle Strategy             7.701000\n",
       "Name: user_score, dtype: float64"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.groupby('Title')['user_score'].mean().sort_values(ascending=False).head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "c8fd40ad-dd40-4e24-933d-444203f0ae3d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Title\n",
       "Mario Tennis: Ultra Smash              20\n",
       "Shin Megami Tensei: Strange Journey    20\n",
       "Pro Evolution Soccer 2018              20\n",
       "The Legend of Dragoon                  20\n",
       "Bleach: The Blade of Fate              20\n",
       "Name: user_score, dtype: int64"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.groupby('Title')['user_score'].count().sort_values(ascending=False).head() "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "15e187a7-deda-4c96-96f6-d8ec4658eb7c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<bound method DataFrame.info of                                 Release Date  Developer  Publisher  Genres  \\\n",
       "Title                                                                        \n",
       "#DRIVE                                    11         11         11      11   \n",
       "#IDARB                                    16         16         16      16   \n",
       "'Splosion Man                             17         17         17      17   \n",
       ".detuned                                  11         11         11      11   \n",
       ".hack//G.U. Last Recode                   12         12         12      12   \n",
       "...                                      ...        ...        ...     ...   \n",
       "moon: Remix RPG Adventure                 16         16         16      16   \n",
       "nail'd                                    18         18         18      18   \n",
       "oOo: Ascension                            10         10         10      10   \n",
       "theHunter: Call of the Wild               19         19         19      19   \n",
       "void tRrLM(); //Void Terrarium            15         15         15      15   \n",
       "\n",
       "                                Product Rating  User Score  \\\n",
       "Title                                                        \n",
       "#DRIVE                                      11          11   \n",
       "#IDARB                                      16          16   \n",
       "'Splosion Man                               17          17   \n",
       ".detuned                                    11          11   \n",
       ".hack//G.U. Last Recode                     12          12   \n",
       "...                                        ...         ...   \n",
       "moon: Remix RPG Adventure                   16          16   \n",
       "nail'd                                      18          18   \n",
       "oOo: Ascension                              10          10   \n",
       "theHunter: Call of the Wild                 19          19   \n",
       "void tRrLM(); //Void Terrarium              15          15   \n",
       "\n",
       "                                User Ratings Count  Platforms Info  \\\n",
       "Title                                                                \n",
       "#DRIVE                                          11              11   \n",
       "#IDARB                                          16              16   \n",
       "'Splosion Man                                   17              17   \n",
       ".detuned                                        11              11   \n",
       ".hack//G.U. Last Recode                         12              12   \n",
       "...                                            ...             ...   \n",
       "moon: Remix RPG Adventure                       16              16   \n",
       "nail'd                                          18              18   \n",
       "oOo: Ascension                                  10              10   \n",
       "theHunter: Call of the Wild                     19              19   \n",
       "void tRrLM(); //Void Terrarium                  15              15   \n",
       "\n",
       "                                Platforms Info Cleaned  Platform Metascores  \\\n",
       "Title                                                                         \n",
       "#DRIVE                                              11                   11   \n",
       "#IDARB                                              16                   16   \n",
       "'Splosion Man                                       17                   17   \n",
       ".detuned                                            11                   11   \n",
       ".hack//G.U. Last Recode                             12                   12   \n",
       "...                                                ...                  ...   \n",
       "moon: Remix RPG Adventure                           16                   16   \n",
       "nail'd                                              18                   18   \n",
       "oOo: Ascension                                      10                   10   \n",
       "theHunter: Call of the Wild                         19                   19   \n",
       "void tRrLM(); //Void Terrarium                      15                   15   \n",
       "\n",
       "                                Platform Metascore Counts  user_id  user_score  \n",
       "Title                                                                           \n",
       "#DRIVE                                                 11       11          11  \n",
       "#IDARB                                                 16       16          16  \n",
       "'Splosion Man                                          17       17          17  \n",
       ".detuned                                               11       11          11  \n",
       ".hack//G.U. Last Recode                                12       12          12  \n",
       "...                                                   ...      ...         ...  \n",
       "moon: Remix RPG Adventure                              16       16          16  \n",
       "nail'd                                                 18       18          18  \n",
       "oOo: Ascension                                         10       10          10  \n",
       "theHunter: Call of the Wild                            19       19          19  \n",
       "void tRrLM(); //Void Terrarium                         15       15          15  \n",
       "\n",
       "[11252 rows x 13 columns]>"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.groupby('Title').count().info"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "e7e7fa61-f0f0-4991-9103-43f535b4f65b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>user_score</th>\n",
       "      <th>total num of user score</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Title</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>#DRIVE</th>\n",
       "      <td>4.780909</td>\n",
       "      <td>11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>#IDARB</th>\n",
       "      <td>6.345000</td>\n",
       "      <td>16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>'Splosion Man</th>\n",
       "      <td>4.370588</td>\n",
       "      <td>17</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>.detuned</th>\n",
       "      <td>5.422727</td>\n",
       "      <td>11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>.hack//G.U. Last Recode</th>\n",
       "      <td>5.703333</td>\n",
       "      <td>12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>moon: Remix RPG Adventure</th>\n",
       "      <td>6.103750</td>\n",
       "      <td>16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>nail'd</th>\n",
       "      <td>5.006111</td>\n",
       "      <td>18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>oOo: Ascension</th>\n",
       "      <td>5.350000</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>theHunter: Call of the Wild</th>\n",
       "      <td>5.320000</td>\n",
       "      <td>19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>void tRrLM(); //Void Terrarium</th>\n",
       "      <td>6.207333</td>\n",
       "      <td>15</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>11252 rows × 2 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                user_score  total num of user score\n",
       "Title                                                              \n",
       "#DRIVE                            4.780909                       11\n",
       "#IDARB                            6.345000                       16\n",
       "'Splosion Man                     4.370588                       17\n",
       ".detuned                          5.422727                       11\n",
       ".hack//G.U. Last Recode           5.703333                       12\n",
       "...                                    ...                      ...\n",
       "moon: Remix RPG Adventure         6.103750                       16\n",
       "nail'd                            5.006111                       18\n",
       "oOo: Ascension                    5.350000                       10\n",
       "theHunter: Call of the Wild       5.320000                       19\n",
       "void tRrLM(); //Void Terrarium    6.207333                       15\n",
       "\n",
       "[11252 rows x 2 columns]"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "userscores = pd.DataFrame(data.groupby('Title')['user_score'].mean())  \n",
    "\n",
    "userscores['total num of user score'] = pd.DataFrame(data.groupby('Title')['user_score'].count()) \n",
    "\n",
    "userscores"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "d408a90b-daf7-4f8f-99a3-002b406ef1d1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>user_score</th>\n",
       "      <th>total num of user score</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Title</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Mario Tennis: Ultra Smash</th>\n",
       "      <td>4.9705</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Shin Megami Tensei: Strange Journey</th>\n",
       "      <td>4.2170</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Pro Evolution Soccer 2018</th>\n",
       "      <td>4.8415</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>The Legend of Dragoon</th>\n",
       "      <td>5.7855</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Bleach: The Blade of Fate</th>\n",
       "      <td>5.2525</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Fight Night Round 4</th>\n",
       "      <td>5.9420</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Nebuchadnezzar</th>\n",
       "      <td>5.4830</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Fighters Uncaged</th>\n",
       "      <td>5.3780</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Naval War: Arctic Circle</th>\n",
       "      <td>4.7255</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Naughty Bear: Panic in Paradise</th>\n",
       "      <td>5.1525</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                     user_score  total num of user score\n",
       "Title                                                                   \n",
       "Mario Tennis: Ultra Smash                4.9705                       20\n",
       "Shin Megami Tensei: Strange Journey      4.2170                       20\n",
       "Pro Evolution Soccer 2018                4.8415                       20\n",
       "The Legend of Dragoon                    5.7855                       20\n",
       "Bleach: The Blade of Fate                5.2525                       20\n",
       "Fight Night Round 4                      5.9420                       20\n",
       "Nebuchadnezzar                           5.4830                       20\n",
       "Fighters Uncaged                         5.3780                       20\n",
       "Naval War: Arctic Circle                 4.7255                       20\n",
       "Naughty Bear: Panic in Paradise          5.1525                       20"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "score_matrix = data.pivot_table(index='user_id', columns='Title', values='user_score', fill_value=0)\n",
    "\n",
    "score_matrix.head()\n",
    "\n",
    "userscores.sort_values('total num of user score', ascending = False).head(10) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "5fc5d74e-2234-4bd5-a2db-260fc67dfc8a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "user_id\n",
       "user_1      5.13\n",
       "user_10     3.20\n",
       "user_100    0.00\n",
       "user_11     0.00\n",
       "user_12     0.00\n",
       "            ... \n",
       "user_95     0.00\n",
       "user_96     0.00\n",
       "user_97     0.00\n",
       "user_98     5.09\n",
       "user_99     3.10\n",
       "Name: Pro Evolution Soccer 2018, Length: 100, dtype: float64"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "game_user_score = score_matrix['Pro Evolution Soccer 2018'] \n",
    "\n",
    "game_user_score"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "6c46d777-9096-4d99-9c64-85f13e53a8ae",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Correlation</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Title</th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>#DRIVE</th>\n",
       "      <td>0.176895</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>#IDARB</th>\n",
       "      <td>-0.025724</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>'Splosion Man</th>\n",
       "      <td>-0.039203</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>.detuned</th>\n",
       "      <td>-0.026495</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>.hack//G.U. Last Recode</th>\n",
       "      <td>-0.029023</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                         Correlation\n",
       "Title                               \n",
       "#DRIVE                      0.176895\n",
       "#IDARB                     -0.025724\n",
       "'Splosion Man              -0.039203\n",
       ".detuned                   -0.026495\n",
       ".hack//G.U. Last Recode    -0.029023"
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "similar_to_game = score_matrix.corrwith(game_user_score)  \n",
    "  \n",
    "corr_drive = pd.DataFrame(similar_to_game, columns =['Correlation']) \n",
    "corr_drive.dropna(inplace = True) \n",
    "  \n",
    "corr_drive.head() "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "cea12c5b-8c4c-491c-8cc3-189766468080",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "corr_drive Sample Data:\n",
      "                         Correlation\n",
      "Title                               \n",
      "#DRIVE                      0.176895\n",
      "#IDARB                     -0.025724\n",
      "'Splosion Man              -0.039203\n",
      ".detuned                   -0.026495\n",
      ".hack//G.U. Last Recode    -0.029023\n",
      "\n",
      "userscores Columns: ['user_score', 'total num of user score']\n",
      "userscores Sample Data:\n",
      "                         user_score  total num of user score\n",
      "Title                                                       \n",
      "#DRIVE                     4.780909                       11\n",
      "#IDARB                     6.345000                       16\n",
      "'Splosion Man              4.370588                       17\n",
      ".detuned                   5.422727                       11\n",
      ".hack//G.U. Last Recode    5.703333                       12\n"
     ]
    }
   ],
   "source": [
    "print(\"corr_drive Sample Data:\")\n",
    "print(corr_drive.head())\n",
    "\n",
    "print(\"\\nuserscores Columns:\", userscores.columns.tolist())\n",
    "print(\"userscores Sample Data:\")\n",
    "print(userscores.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "edba5e21-ff05-443f-b17c-1ac1fe5e0a38",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Top 10 Correlations:\n",
      "                                               Correlation  \\\n",
      "Title                                                        \n",
      "Pro Evolution Soccer 2018                         1.000000   \n",
      "Anno 2070                                         0.559420   \n",
      "Watchmen: The End Is Nigh Complete Experience     0.465746   \n",
      "Star Conflict                                     0.447682   \n",
      "Aliens: Fireteam Elite                            0.433820   \n",
      "ONRUSH                                            0.422457   \n",
      "Hatoful Boyfriend: Holiday Star                   0.413475   \n",
      "Train Sim World                                   0.406345   \n",
      "Tempest 4000                                      0.399536   \n",
      "Call of Duty: Black Ops - First Strike            0.389230   \n",
      "\n",
      "                                               total num of user score  \n",
      "Title                                                                   \n",
      "Pro Evolution Soccer 2018                                           20  \n",
      "Anno 2070                                                           11  \n",
      "Watchmen: The End Is Nigh Complete Experience                       20  \n",
      "Star Conflict                                                       17  \n",
      "Aliens: Fireteam Elite                                              19  \n",
      "ONRUSH                                                              12  \n",
      "Hatoful Boyfriend: Holiday Star                                     12  \n",
      "Train Sim World                                                     17  \n",
      "Tempest 4000                                                        15  \n",
      "Call of Duty: Black Ops - First Strike                              17  \n",
      "\n",
      "Number of missing 'total num of user score': 0\n",
      "\n",
      "Correlations with 'total num of user score' > 10:\n",
      "                                               Correlation  \\\n",
      "Title                                                        \n",
      "Pro Evolution Soccer 2018                         1.000000   \n",
      "Anno 2070                                         0.559420   \n",
      "Watchmen: The End Is Nigh Complete Experience     0.465746   \n",
      "Star Conflict                                     0.447682   \n",
      "Aliens: Fireteam Elite                            0.433820   \n",
      "\n",
      "                                               total num of user score  \n",
      "Title                                                                   \n",
      "Pro Evolution Soccer 2018                                           20  \n",
      "Anno 2070                                                           11  \n",
      "Watchmen: The End Is Nigh Complete Experience                       20  \n",
      "Star Conflict                                                       17  \n",
      "Aliens: Fireteam Elite                                              19  \n"
     ]
    }
   ],
   "source": [
    "corr_drive = corr_drive.drop(columns=['total num of user score'], errors='ignore')\n",
    "\n",
    "corr_drive_sorted = corr_drive.sort_values('Correlation', ascending=False).head(10)\n",
    "\n",
    "merged_corr_drive = corr_drive_sorted.join(userscores['total num of user score'], how='left')\n",
    "\n",
    "print(\"Top 10 Correlations:\")\n",
    "print(merged_corr_drive)\n",
    "\n",
    "missing_scores = merged_corr_drive['total num of user score'].isnull().sum()\n",
    "print(f\"\\nNumber of missing 'total num of user score': {missing_scores}\")\n",
    "\n",
    "\n",
    "merged_corr_drive.dropna(subset=['total num of user score'], inplace=True)\n",
    "\n",
    "high_score_corr = merged_corr_drive[merged_corr_drive['total num of user score'] > 10].sort_values('Correlation', ascending=False).head()\n",
    "\n",
    "print(\"\\nCorrelations with 'total num of user score' > 10:\")\n",
    "print(high_score_corr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b4676a1d-537e-4cd7-8869-7c6ee1c6fc36",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
